### ISSUE TITLE
Crash selecting preset category drill down button

### ISSUE THREAD

**Issue by nerdsosky** [willowtreeapps/vocable-android#186]
The app is crashing whenever selecting the button for a preset category which takes the user to the menu to hide the category.

Steps:
1. Launch the application
2. Select the setting button
3. Select the Categories option
4. Select the drill down arrow for a preset category ("Basic Needs", "General", etc...)

Result: Application Crashes

Build: V1.3 Google Play Store Build

Device: Samsung S7 Android 8.0.0

Emulator: Pixel 3 Android 9.0

`2020-04-28 10:58:27.724 9971-9971/com.willowtree.vocable E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.willowtree.vocable, PID: 9971
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.Exception: View binding has been accessed after the view has been destroyed
        at com.willowtree.vocable.BaseFragment.getBinding(BaseFragment.kt:20)
        at com.willowtree.vocable.settings.EditCategoriesFragment.access$getBinding$p(EditCategoriesFragment.kt:16)
        at com.willowtree.vocable.settings.EditCategoriesFragment$subscribeToViewModel$2.onChanged(EditCategoriesFragment.kt:141)
        at com.willowtree.vocable.settings.EditCategoriesFragment$subscribeToViewModel$2.onChanged(EditCategoriesFragment.kt:16)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by jennydoesthings** [comment]
Confirm fixed as of 1.4
